image:
  repository: major1201/frps
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

frp:
  token: BCEA79FA-1DE3-4ECF-913E-A4F2CA29017F

service:
  type: LoadBalancer
  ports:
    - port: 7000
      targetPort: 7000
      protocol: TCP
      name: frp
